/* This file is generated by pcode_autog-1.16.6
** Copyright(c) HALX99, ALL RIGHTS RESERVED.
**
** Purpose: Includes
**
*/
#ifndef _PCODE_AUTOG_CLIENT_INCLUDES_H_
#define _PCODE_AUTOG_CLIENT_INCLUDES_H_


#include "ibinarystream.h"
#include "obinarystream.h"
#include "oslib.h"
#include <assert.h>
#include <vector>
#include <iomanip>


#endif

