/* This file is generated by pcode_autog-1.15.9
** Copyright(c) Link.Doex, ALL RIGHTS RESERVED.
**
** Purpose: contains basic structures for protocol
**
*/
#ifndef _PCODE_AUTOG_SERVER_STRUCTURES_H_
#define _PCODE_AUTOG_SERVER_STRUCTURES_H_


#include "pcode_autog_server_includes.h"
namespace structures {

struct RealtimeFieldCellInfo {
    int32_t                 sid;
    uint8_t                 scolor;
    uint8_t                 sloc;
    uint16_t                slevel;
    int8_t                  sstate;
    bool                    key;
    int8_t                  swait;
    float                   spower;
    float                   spowerv;
    float                   shurtac;
    float                   atkadd;
    uint8_t                 sl_index1;
    uint8_t                 sl_index2;
};

struct RealtimeFieldInfo {
    std::string             user_name;
    uint32_t                equip_id;
    uint32_t                hero_id;
    uint16_t                hero_lv;
    uint32_t                hero_hp;
    uint32_t                hero_mp;
    uint16_t                idles;
    uint16_t                wrecord;
    std::string             append_data;
};

};



#endif

