/* This file is generated by pcode_autog
** Copyright(c) xml3see, ALL RIGHTS RESERVED.
**
** Purpose: Includes
**
*/
#ifndef _PROTOCOL_INCLUDES_H_
#define _PROTOCOL_INCLUDES_H_


#include "xxpiedef.h"
#include <iomanip>


#endif

