-- This file is generated by pcode_autog-1.19.5
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains some constants defininations
--
--
proto = proto or {}

proto.numbers = {
    CID_SIMPLE1 = 101, 
}
