-- This file is generated by x-studio365 10.0.3300.990 © 2018, All rights reserved.
-- Module: masio, <please write module description>
-- Author: halx99
-- Create Date: [2018-12-01 14:33:48]

local masio = {
    CHANNEL_TCP_CLIENT = 1,
    CHANNEL_TCP_SERVER = 2,
    MASIO_OPT_CONNECT_TIMEOUT = 1,
    MASIO_OPT_SEND_TIMEOUT = 2,
    MASIO_OPT_RECONNECT_TIMEOUT = 3,
    MASIO_OPT_DNS_CACHE_TIMEOUT = 4,
    MASIO_OPT_DEFER_EVENT = 5,
    MASIO_OPT_TCP_KEEPALIVE = 6,
    MASIO_OPT_RESOLV_FUNCTION = 7,
    MASIO_OPT_LOG_FILE = 8,
    MASIO_OPT_LFIB_PARAMS = 9,
    MASIO_EVENT_CONNECT_RESPONSE = 0,
    MASIO_EVENT_CONNECTION_LOST = 1,
    MASIO_EVENT_RECV_PACKET = 2
}

return masio
