-- This file is generated by pcode_autog-1.18.12
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains all protocol message definiations and codec function
--          implementations
--
--
-- Implement all pure lua protocol decode functions.
require 'protocol_enums'

proto.d101 = function(ibs)
    local msg = proto.begin_decode(ibs);

    msg.id = ibs:read_i8(); 
    msg.value1 = ibs:read_u16(); 
    msg.value2 = ibs:read_i32(); 
    msg.value3 = ibs:read_bool(); 
    msg.value4 = ibs:read_f(); 
    msg.value6 = ibs:read_lf(); 
    msg.uname = crypto.rsa.pub_decrypt(ibs:read_string(), get_file_content('masio-rsa-public.pem'), PaddingMode.PKCS1_PADDING);
    msg.passwd = crypto.rsa.pri_decrypt(ibs:read_string(), get_file_content('masio-rsa-private.pem'), PaddingMode.PKCS1_OAEP_PADDING)

    return msg;
end


