/* This file is generated by pcode_autog-1.16.10
** Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
**
** Purpose: contains some constants defininations
**
*/
#ifndef _PCODE_AUTOG_CLIENT_CONSTANTS_H_
#define _PCODE_AUTOG_CLIENT_CONSTANTS_H_

enum {
    CID_LOGIN_REQ = 101,
    CID_LOGIN_RESP = 102,
    CID_LOCAL_ERROR_INFO = 0x7fff,
    CID_MSG_PEER_ENDPOINT_REQ = 1001,
};

#endif

