-- This file is generated by pcode_autog-1.16.6
-- Copyright(c) HALX99, ALL RIGHTS RESERVED.
--
-- Purpose: contains some constants defininations
--
--
pcode_autog = pcode_autog or {}

pcode_autog.CID_LOGIN_REQ = 101;
pcode_autog.CID_LOGIN_RESP = 102;
pcode_autog.CID_LOCAL_ERROR_INFO = 0x7fff;
pcode_autog.CID_MSG_PEER_ENDPOINT_REQ = 1001;
pcode_autog.CID_MSG_PEER_ENDPOINT_RESP= 1002;
pcode_autog.CID_MSG_GET_FRIENDLIST_REQ = 1003;
pcode_autog.CID_MSG_GET_FRIENDLIST_RESP = 1004;

