-- This file is generated by pcode_autog-1.16.6
-- Copyright(c) HALX99, ALL RIGHTS RESERVED.
--
-- Purpose: contains some constants defininations
--
--
pcode_autog = pcode_autog or {}

pcode_autog.CID_MSG_PACKET = 1;
pcode_autog.CID_LOCAL_ERROR_INFO = 0x7fff;

