-- This file is generated by pcode_autog-1.16.10
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains some constants defininations
--
--
zysj = zysj or {}

zysj.CID_LOGIN_REQ = 101;
zysj.CID_LOGIN_RESP = 102;
zysj.CID_LOCAL_ERROR_INFO = 0x7fff;
zysj.CID_MSG_PEER_ENDPOINT_REQ = 1001;
zysj.CID_MSG_PEER_ENDPOINT_RESP= 1002;
zysj.CID_MSG_GET_FRIENDLIST_REQ = 1003;
zysj.CID_MSG_GET_FRIENDLIST_RESP = 1004;

