/* This file is generated by pcode_autog-1.16.6
** Copyright(c) HALX99, ALL RIGHTS RESERVED.
**
** Purpose: Includes
**
*/
#ifndef _PCODE_AUTOG_CLIENT_INCLUDES_H_
#define _PCODE_AUTOG_CLIENT_INCLUDES_H_


#include "purelib/utils/ibinarystream.h"
#include "purelib/utils/obinarystream.h"
#include "purelib/utils/oslib.h"
#include <assert.h>
#include <vector>
#include <iomanip>


#endif

