-- This file is generated by pcode_autog-1.16.10
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains all protocol message definiations and codec function
--          implementations
--
--
-- Implement all pure lua protocol decode functions.
require "protocol_enums"

proto.d1002 = function(ibs)
    local msg = {}

    msg.user_id = ibs:readui32(); 
    msg.addr = ibs:readstring();
    msg.port = ibs:readui16(); 

    return msg;
end

proto.d1004 = function(ibs)
    local msg = {}

    msg.result = ibs:readi8(); 
    msg.user_id = ibs:readui32(); 
    local friends_size = ibs:readui16();
    msg.friends = {};
    local friendsindex = 0;
    while(friendsindex < friends_size) do
        friendsindex = friendsindex + 1;
        msg.friends[friendsindex] = {};
        msg.friends[friendsindex].user_id = ibs:readui32(); 
        msg.friends[friendsindex].user_name = ibs:readstring();
        msg.friends[friendsindex].equip_id = ibs:readui32(); 
        msg.friends[friendsindex].hero_id = ibs:readui32(); 
        msg.friends[friendsindex].hero_lv = ibs:readui16(); 
        msg.friends[friendsindex].hero_hp = ibs:readui32(); 
        msg.friends[friendsindex].hero_mp = ibs:readui32(); 
    end

    return msg;
end


