-- This file is generated by pcode_autog-1.16.10
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains all protocol message definiations and codec function
--          implementations
--
--
-- Implement all pure lua protocol encode functions.
require "protocol_enums"

proto.e1003 = function(msg)
    -- create message header stream.
    local obs = proto.obstream:create(proto.numbers.CID_MSG_GET_FRIENDLIST_REQ);

    -- encode message fields.
    obs:writeui32(msg.user_id);

    return obs;
end


