-- This file is generated by pcode_autog-1.16.10
-- Copyright(c) Lake.Deal, ALL RIGHTS RESERVED.
--
-- Purpose: contains some constants defininations
--
--
proto = proto or {}

proto.numbers = enum_class {
    CID_LOGIN_REQ = 101, 
    CID_LOGIN_RESP = 102, 
    CID_LOCAL_ERROR_INFO = 0x7fff, 
    CID_MSG_PEER_ENDPOINT_REQ = 1001, 
    CID_MSG_PEER_ENDPOINT_RESP= 1002, 
    CID_MSG_GET_FRIENDLIST_REQ = 1003, 
    CID_MSG_GET_FRIENDLIST_RESP = 1004, 
}
