name: freebsd

on: push

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg install -y git
          pkg install -y cmake
          pkg install -y python3
          # required by mbedtls-3.3.0
          pkg install -y py39-pip
          pip install jsonschema jinja2
          # install perl5, localtion: /usr/local/bin
          pkg search perl5
          pkg search perl5 | cut -d' ' -f1 | head -n 1 | xargs pkg install -y
          perl -v
        run: |
          echo Building on freebsd...
          cmake -G "Unix Makefiles" -S . -Bbuild -DYASIO_SSL_BACKEND=2
          cmake --build build --config Release
          echo run test icmp on freebsd...
          ./build/tests/icmp/icmptest

